### ISSUE TITLE
bugfix

### ISSUE THREAD

**Issue by SeekingFunChild** [Vatuu/Zelda-BotW-Tools#1]
# modify these place can make it work:
public enum NodeType : byte
{
	STRING = 0xA0,
	ARRAY = 0xC0,
	DICTIONARY = 0xC1,
	STRING_ARRAY = 0xC2,
	BOOLEAN = 0xD0,
	SHORT_INTEGER = 0xD1,//modified
	FLOAT = 0xD2,
        LONG_INTEGER = 0xD3//modified
}
              
switch(type)
{
	case NodeType.STRING:
		return stringArray[reader.ReadInt32()];
	case NodeType.BOOLEAN:
		return reader.ReadInt32()!=0; //modified reader.ReadBoolean() =>reader.ReadInt32()!=0
	case NodeType.SHORT_INTEGER:
		return reader.ReadInt32();
	case NodeType.FLOAT:
		return reader.ReadSingle();
	case NodeType.LONG_INTEGER: //new add
		return reader.ReadInt32();
	default:
		throw new ByamlException($"Unknown Node Type '{((byte)type).ToString("X2")}'!");
}

NodeType type = (NodeType) ((byte)lengthType & 0x0000FFFF);  //modified 0x000000FF => 0x0000FFFF

**Comment by Vatuu** [comment]
Fixed everything, don't worry about it.

D3 is actually a crc32 hash.
